### ISSUE TITLE
Issue template to add projects, with checklist?

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/contribute.dev#18]
With `contribute.dev`, we want to:
- show aspiring OSS newcomers cool projects they could join & start contributing to today
- show maintainers how to make their projects newcomer-friendly, esp. by fully automating their dev setup

Maintainers will likely file issues, requesting to be added to the list. In order to help/guide them through the process, we should have an issue template with an efficient / hassle-free checklist of any steps to do or criteria to meet, that goes straight to the point in explaining what's required and how to achieve it, with links to helpful resources.

I suggest the following criteria (but please share thoughts / suggest changes):

- [x] Project should have a fully automated setup: ready in one click / one minute, ideally fully online, with *nothing* to install or configure on your computer first. It's relatively easy achieve this with Gitpod, by following [this tutorial](https://www.gitpod.io/blog/gitpodify/)
- [x] Project should be interesting/exciting/popular to contribute to: minimum of 1000 stars?
- [x] Project should have an active community: active Pulse? Minimum number of contributors?
- [x] Project should have basic newcomer onboarding: minimal contributing docs, links to good first issue...
- Exceptions are always possible. Please reach out if you think your project would be a great fit, by explaining how your project gives new contributors a fantastic first experience. Or reach out with any question, we're super happy to collaborate. :)

**Comment by jankeromnes** [comment]
Tentative template draft:

---

## Is your project's development setup fully automated? How to use it?

## Why is your project interesting/exciting/popular to contribute to?

## Does your project have an active community?

## Does your project have basic newcomer onboarding docs? (e.g. CONTRIBUTING.md, good-first-issues...)
